name: primer workflow
run-name: Workflow para entender el funcionamiento automatizado

on: push

jobs:
	example_job:
		runs-on: ubuntu-latest
		steps:
			- run: echo "hola workflow"
			- run: echo "siguiente"
